Code length reduction
kazzkiq/balloon.css pull request #143
Opened 2020-06-16 13:25 UTC by smartcrash

Reduce balloon.min.css bundled file size from ~8.1KB to ~6.6KB preserving the same appearance and interface.

2020-06-16 14:04 UTC, kazzkiq requested changes
Pretty good overall refactoring. I see no issues with the code other than the typo. Will run some manual tests to confirm the behavior stays the same (especially on mobile).

2020-06-16 14:04 UTC, kazzkiq commented on src/_mixins.scss
> +    @error '[balloon] The $direction parameter most be one of: `#{map-keys($DIRECTIONS)}, `#{$direction}` was given.';
Small typo, `most` should be `must`.

2020-06-16 19:34 UTC, smartcrash commented
I removed the typo 👌

2020-06-30 19:38 UTC, kazzkiq commented
Finally got time to do some regressive testing and everything seems ok.

That's a great contribution. Thanks!

2020-06-30 19:39 UTC, merged